const HOST = "http://10.226.38.37:8000";
export const LOCAL = "http://localhost:5173";
export const REGISTER = `${HOST}/userAccount/register`;
export const LOGIN = `${HOST}/userAccount/login`;
export const AUTHENTICATION = `${HOST}/userInfo/authentication`;
export const UPDATEAVATAR = `${HOST}/userInfo/updateAvatar`;
export const UPDATEDIRECTORYDEPENDENCE = `${HOST}/userInfo/updateDirectoryDependence`;
export const UPDATEUSERFILE = `${HOST}/userInfo/updateUserFile`
export const TEXTDEAL = `${HOST}/aiTextHelper/textDeal`;
export const AIREQUEST = `${HOST}/aiTextHelper/customize`;
